# Generated by Django 4.1.5 on 2023-01-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
