# Generated by Django 4.1.5 on 2023-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_email_client_name_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=13),
        ),
    ]
