# Generated by Django 4.1.5 on 2023-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_remove_client_email_remove_client_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
            preserve_default='True',
        ),
    ]
